# Generated by Django 4.1.4 on 2022-12-30 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_planner', '0002_alter_users_creation_time_alter_users_name_teams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='team',
        ),
        migrations.AddField(
            model_name='tasks',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_planner.boards'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_planner.users'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'In progress'), (3, 'Complete')], default=1),
        ),
    ]
