# Generated by Django 4.1.4 on 2022-12-31 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_planner', '0003_remove_tasks_team_tasks_board_tasks_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='project_planner.teams'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_planner.boards'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_planner.users'),
        ),
    ]
